# -*- coding: utf-8 -*-
{
    "name": "EHCS Evo-Tech Website",
    "summary": """ Evo-Tech Website. """,
    "author": "ERP Harbor Consulting Services",
    "website": "http://www.erpharbor.com",
    "version": "13.0.1.0.0",
    "category": "Website",
    "depends": [
        "theme_odoo_experts","website",
    ],
    "data": [
        "data/menu.xml",
        "data/filamente_sub.xml",
        "data/industry_sub.xml",
        "data/about_sub.xml",
        "data/customer_sub.xml",
        "views/web_asset_template.xml",
        "views/website.xml",
        "views/home.xml",
        "views/filamente.xml",
        "views/branchen.xml",
        "views/ueber_uns.xml",
        "views/kunden_area.xml",
        "views/contactus.xml",
        "views/dienstleistung.xml",
        "views/mega_menu.xml",
        
        "views/printer_submenu_one.xml",
        "views/printer_submenu_two.xml",
        "views/finanzierung_submenu.xml",
        
        "views/filamente/filamente_submenu_one.xml",
        "views/filamente/filamente_submenu_two.xml",
        "views/filamente/filamente_submenu_three.xml",
        "views/filamente/filamente_submenu_four.xml",
        "views/filamente/filamente_submenu_five.xml",
        "views/filamente/filamente_submenu_six.xml",
        "views/filamente/filamente_submenu_seven.xml",
        "views/filamente/filamente_submenu_eight.xml",
        "views/filamente/filamente_submenu_nine.xml",
        "views/filamente/filamente_submenu_ten.xml",
        "views/filamente/filamente_submenu_ele.xml",
        "views/filamente/filamente_submenu_twe.xml",
        "views/filamente/filamente_submenu_thirteen.xml",
        "views/filamente/filamente_submenu_fourteen.xml",
        "views/filamente/filamente_submenu_fifty.xml",
        "views/filamente/filamente_submenu_sixteen.xml",
        
        "views/industry/automotive.xml",
        "views/industry/educational.xml",
        "views/industry/mechanical.xml",
        "views/industry/prototype.xml",
        "views/industry/serial.xml",
        "views/industry/tool-fixture.xml",
        
        "views/about/academy.xml",
        "views/about/presse.xml",
        "views/about/jobs.xml",
        "views/about/termine.xml",
        "views/about/event_opening.xml",
        
        "views/customer/kvp.xml",
        "views/customer/handbücher.xml",
        "views/customer/support.xml",
        "views/customer/firmware.xml",
        "views/customer/simplify.xml",
        "views/customer/know_how.xml",
        "views/customer/rapid_prototyping.xml",
        "views/customer/simplify3d.xml",
        
        "views/simplify3d_tab/additions.xml",
        "views/simplify3d_tab/advanced.xml",
        "views/simplify3d_tab/extruder.xml",
        "views/simplify3d_tab/infill.xml",
        "views/simplify3d_tab/layer.xml",
        "views/simplify3d_tab/other.xml",
        "views/simplify3d_tab/speeds.xml",
        "views/simplify3d_tab/support.xml",
        "views/simplify3d_tab/temperature.xml",
        
        "views/case_study.xml",
        "views/quotation.xml",
        "views/metusan.xml",
        "views/smart_labs.xml",
        "views/cnc_academy.xml",
        "views/inocon.xml",
        "views/kolm_motoren.xml",
    ],
    "qweb": [
        # "static/src/xml/*.xml",
    ],
}
